# Generated by Django 5.1.1 on 2024-10-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorychangelog',
            name='change_details',
            field=models.JSONField(default={}, verbose_name='Change Details'),
            preserve_default=False,
        ),
    ]
