# Generated by Django 5.1.1 on 2024-10-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_remove_inventorychangelog_change_amount_nonzero_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventorychangelog',
            constraint=models.CheckConstraint(condition=models.Q(('change_amount', 0), _negated=True), name='change_amount_nonzero'),
        ),
    ]
