# Generated by Django 5.1.1 on 2024-10-03 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0005_alter_inventorychangelog_change_details'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventorychangelog',
            name='change_amount_nonzero',
        ),
        migrations.RemoveField(
            model_name='inventorychangelog',
            name='change_amount',
        ),
        migrations.AddField(
            model_name='inventorychangelog',
            name='change_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Change in Price'),
        ),
        migrations.AddField(
            model_name='inventorychangelog',
            name='change_quantity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-10000), django.core.validators.MaxValueValidator(10000)], verbose_name='Change in Quantity'),
        ),
        migrations.AlterField(
            model_name='inventorychangelog',
            name='change_details',
            field=models.TextField(blank=True, verbose_name='Change Details'),
        ),
        migrations.AddConstraint(
            model_name='inventorychangelog',
            constraint=models.CheckConstraint(condition=models.Q(('change_quantity__isnull', False), ('change_price__isnull', False), _connector='OR'), name='quantity_or_price_nonnull'),
        ),
    ]
