# Generated by Django 5.1.1 on 2024-10-03 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0008_inventorychangelog_quantity_or_price_nonnull'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventorychangelog',
            name='quantity_or_price_nonnull',
        ),
    ]
