# Generated by Django 5.1.1 on 2024-10-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0009_remove_inventorychangelog_quantity_or_price_nonnull'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventorychangelog',
            constraint=models.CheckConstraint(condition=models.Q(('change_quantity__isnull', False), ('change_price__isnull', False), _connector='OR'), name='quantity_or_price_nonnull'),
        ),
    ]
