# Generated by Django 5.1.1 on 2024-10-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0010_inventorychangelog_quantity_or_price_nonnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=0, verbose_name='Low Stock Threshold'),
        ),
    ]
