# Generated by Django 5.1.1 on 2024-10-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_inventorychangelog_change_details'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventorychangelog',
            name='change_amount_nonzero',
        ),
        migrations.AlterField(
            model_name='inventorychangelog',
            name='change_details',
            field=models.JSONField(default=dict, verbose_name='Change Details'),
        ),
    ]
