# Generated by Django 5.1.1 on 2024-10-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0004_inventorychangelog_change_amount_nonzero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorychangelog',
            name='change_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='Change Details'),
        ),
    ]
