# Generated by Django 5.1.1 on 2024-10-03 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0006_remove_inventorychangelog_change_amount_nonzero_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventorychangelog',
            name='quantity_or_price_nonnull',
        ),
    ]
